### ISSUE TITLE
Addon calls SendAddonMessage hundreds of times per minute to raid while in batteground

### ISSUE THREAD

**Issue by aa-chrismcfadyen** [AzerPUG/ToolTips#10]
And thus spams your chat window with "You are not in a raid group".  Even if you don't get the error messages, it still causes a massive amount of lag.

IsInRaid() does not seem to do what you want it to do, as it returns true any time you are in a raid-like group, including LFR and random BGs, not ones that are valid for /ra

Other addons use

UnitInBattleground("player") ~= nil

or

(not IsInRaid(LE_PARTY_CATEGORY_HOME) and IsInRaid(LE_PARTY_CATEGORY_INSTANCE)) and "INSTANCE_CHAT" or "RAID"

to switch between raid chat and instance chat.

However, there's still the problem of sending **far too** many addon message and lagging the user badly.

**Comment by Arco-Dielhof** [comment]
Heyy, thanx for letting us know and sorry for the inconvenience!
I will try to get a fix out for this ASAP!

If you would be interested in helping me test a potential quick-fix, contact me on Discord: Tex#1991
