### ISSUE TITLE
LUA Error curToolTipItem

### ISSUE THREAD

**Issue by Breakerzeus** [AzerPUG/ToolTips#19]
10x AzerPUGsToolTips\ToolTips.lua:163: attempt to index local 'curToolTipItem' (a nil value)
[string "@AzerPUGsToolTips\ToolTips.lua"]:163: in function `SearchGenericUpgradeableItem'
[string "@AzerPUGsToolTips\ToolTips.lua"]:15: in function <AzerPUGsToolTips\ToolTips.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@BankItems\BankItems-9.0.2.3.lua"]:6728: in function <BankItems\BankItems.lua:6726>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@BankItems\BankItems-9.0.2.3.lua"]:6771: in function <BankItems\BankItems.lua:6769>
[string "=[C]"]: in function `SetHyperlink'
[string "@BestInSlotRedux\Frames\FramesCore.lua"]:228: in function `GetItemTooltip'
[string "@BestInSlotRedux\Frames\FramesCore.lua"]:337: in function <BestInSlotRedux\Frames\FramesCore.lua:331>
[string "=[C]"]: ?
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Masque\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Masque\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Masque\Libs\AceGUI-3.0-41\widgets\AceGUIWidget-InteractiveLabel.lua"]:15: in function <...AceGUI-3.0\widgets\AceGUIWidget-InteractiveLabel.lua:14>

Locals:
self = <table> {
 GetLegendaryUpgradeInfo = <function> defined @AzerPUGsToolTips\ToolTips.lua:123
 CheckShadowlandsLegendaryItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:105
 GetSpecificAddonVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:318
 ItemUpgrades = <table> {
 }
 FillOptionsPanel = <function> defined @AzerPUGsToolTips\ToolTips.lua:85
 CheckDominationShardItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:215
 StackUpgradeCosts = <function> defined @AzerPUGsToolTips\ToolTips.lua:251
 SearchGenericUpgradeableItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:138
 Currencies = <table> {
 }
 OnLoadCore = <function> defined @AzerPUGsToolTips\ToolTips.lua:21
 ReceiveVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:303
 OnEvent = <function> defined @AzerPUGsToolTips\ToolTips.lua:339
 OnLoadSelf = <function> defined @AzerPUGsToolTips\ToolTips.lua:31
 LegendaryItemUpgrades = <table> {
 }
 SetLegendaryToolTip = <function> defined @AzerPUGsToolTips\ToolTips.lua:177
 DelayedExecution = <function> defined @AzerPUGsToolTips\ToolTips.lua:268
 ShardUpgrades = <table> {
 }
 OnLoadBoth = <function> defined @AzerPUGsToolTips\ToolTips.lua:13
 ShareVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:283
 Events = <table> {
 }
}
clipAfter = 15
searchValue = "Upgrade Level: "
ttname = "GameTooltip"
(for index) = 4
(for limit) = 13
(for step) = 1
i = 4
left = GameTooltipTextLeft4 {
 0 = <userdata>
}
text = "Upgrade Level: 1/12"
priceToMax = nil
curToolTipItem = nil
_ = "Purge Protocol Legwraps"
itemLink = "|cffa335ee|Hitem:180107::::::::60:267::23:1:3524::::::|h[Purge Protocol Legwraps]|h|r"
itemString = "-cffa335ee-Hitem:180107::::::::60:267::23:1:3524::::::-h[Purge Protocol Legwraps]-h-r"
_ = "-cffa335ee-Hitem"
_ = "180107"
_ = ""
_ = ""
_ = ""
_ = ""
_ = ""
_ = ""
_ = ""
_ = "60"
_ = "267"
_ = ""
_ = "23"
NumBonusIDs = "1"
BonusID1 = "3524"
BonusID2 = ""
BonusID3 = ""
BonusID4 = ""
BonusID5 = ""
BonusID6 = ""
bonusIDList = <table> {
 1 = 3524
}
displayIcon = ""
(*temporary) = 1
(*temporary) = 1
(*temporary) = 1
(*temporary) = nil
(*temporary) = 3524
(*temporary) = ""
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'curToolTipItem' (a nil value)"

**Comment by Arco-Dielhof** [comment]
Heyya, sorry for the late reaction, I have been extremely busy. We will look into this today, seemingly it happens when in combination with Masque, which is doing some weird things with the tooltips so they are not usable in the normal way anymore (other addons that do tooltip stuff have reported similar issue in combination with Masque...)

**Comment by Arco-Dielhof** [comment]
Newest update should, at least, prevent the error, but it might not list the info. Please let us know if you are still encountering an issue!
