### ISSUE TITLE
two lua error

### ISSUE THREAD

**Issue by CrisReus** [AzerPUG/ToolTips#20]
8x AzerPUGsToolTips\ToolTips.lua:125: bad argument #2 to 'strsplit' (string expected, got nil)
[string "=[C]"]: in function `strsplit'
[string "@AzerPUGsToolTips\ToolTips.lua"]:125: in function `GetLegendaryUpgradeInfo'
[string "@AzerPUGsToolTips\ToolTips.lua"]:113: in function `CheckShadowlandsLegendaryItem'
[string "@AzerPUGsToolTips\ToolTips.lua"]:16: in function <AzerPUGsToolTips\ToolTips.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals:
(*temporary) = ":"
(*temporary) = nil
(*temporary) = "string expected, got nil"

==============================================================================
144x AzerPUGsToolTips\ToolTips.lua:217: attempt to index local 'itemLink' (a nil value)
[string "@AzerPUGsToolTips\ToolTips.lua"]:217: in function `CheckDominationShardItem'
[string "@AzerPUGsToolTips\ToolTips.lua"]:17: in function <AzerPUGsToolTips\ToolTips.lua:14>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetTrainerService'
[string "*:OnEnter"]:3: in function <[string "*:OnEnter"]:1>

Locals:
self = <table> {
 GetLegendaryUpgradeInfo = <function> defined @AzerPUGsToolTips\ToolTips.lua:123
 CheckShadowlandsLegendaryItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:105
 GetSpecificAddonVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:318
 ItemUpgrades = <table> {
 }
 FillOptionsPanel = <function> defined @AzerPUGsToolTips\ToolTips.lua:85
 CheckDominationShardItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:215
 StackUpgradeCosts = <function> defined @AzerPUGsToolTips\ToolTips.lua:251
 SearchGenericUpgradeableItem = <function> defined @AzerPUGsToolTips\ToolTips.lua:138
 Currencies = <table> {
 }
 OnLoadCore = <function> defined @AzerPUGsToolTips\ToolTips.lua:21
 ReceiveVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:303
 OnEvent = <function> defined @AzerPUGsToolTips\ToolTips.lua:339
 OnLoadSelf = <function> defined @AzerPUGsToolTips\ToolTips.lua:31
 LegendaryItemUpgrades = <table> {
 }
 SetLegendaryToolTip = <function> defined @AzerPUGsToolTips\ToolTips.lua:177
 DelayedExecution = <function> defined @AzerPUGsToolTips\ToolTips.lua:268
 ShardUpgrades = <table> {
 }
 OnLoadBoth = <function> defined @AzerPUGsToolTips\ToolTips.lua:13
 ShareVersion = <function> defined @AzerPUGsToolTips\ToolTips.lua:283
 Events = <table> {
 }
}
_ = nil
itemLink = nil
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'itemLink' (a nil value)"

**Comment by Arco-Dielhof** [comment]
Heyya, sorry for the late reaction, I have been extremely busy. We will look into this today, seemingly it happens when in combination with Masque, which is doing some weird things with the tooltips so they are not usable in the normal way anymore (other addons that do tooltip stuff have reported similar issue in combination with Masque...)

**Comment by Arco-Dielhof** [comment]
Newest update should, at least, prevent the error, but it might not list the info. Please let us know if you are still encountering an issue!

**Comment by CrisReus** [comment]
thanks for your work. 
I will always support your work.
