### ISSUE TITLE
Missing INVTYPE_CLOAK

### ISSUE THREAD

**Issue by Markiv3** [AzerPUG/ToolTips#27]
Fixed the below error when mousing over a cloak/back by adding INVTYPE_CLOAK index in AZP.ToolTips.StaticSlotValorCost array in dataTables.lua.

AzerPUGsToolTips/ToolTips.lua:167: attempt to perform arithmetic on local 'perLevelUpgradeCost' (a nil value)
[string "@AzerPUGsToolTips/ToolTips.lua"]:167: in function `SearchGenericUpgradeableItem'
[string "@AzerPUGsToolTips/ToolTips.lua"]:16: in function <AzerPUGsToolTips/ToolTips.lua:15>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML/PaperDollFrame.lua"]:1752: in function `PaperDollItemSlotButton_OnEnter'
[string "*PaperDollFrame.xml:47_OnEnter"]:1: in function <[string "*PaperDollFrame.xml:47_OnEnter"]:1>

Locals:
self = <table> {
 GetSpecificAddonVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:274
 WeapValorCostList = <table> {
 }
 ItemUpgrades = <table> {
 }
 FillOptionsPanel = <function> defined @AzerPUGsToolTips/ToolTips.lua:89
 GetUpgradeCostForItem = <function> defined @AzerPUGsToolTips/ToolTips.lua:204
 SearchGenericUpgradeableItem = <function> defined @AzerPUGsToolTips/ToolTips.lua:141
 RankBonusID = <table> {
 }
 OnLoadCore = <function> defined @AzerPUGsToolTips/ToolTips.lua:25
 ReceiveVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:259
 OnEvent = <function> defined @AzerPUGsToolTips/ToolTips.lua:296
 OnLoadSelf = <function> defined @AzerPUGsToolTips/ToolTips.lua:35
 Currencies = <table> {
 }
 Events = <table> {
 }
 ShareVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:239
 DelayedExecution = <function> defined @AzerPUGsToolTips/ToolTips.lua:224
 OnLoadBoth = <function> defined @AzerPUGsToolTips/ToolTips.lua:14
 StaticSlotValorCost = <table> {
 }
 StackUpgradeCosts = <function> defined @AzerPUGsToolTips/ToolTips.lua:187
}
clipAfter = 15
searchValue = "Upgrade Level: "
_ = "Potion-Stained Cloak"
itemLink = "|cffa335ee|Hitem:193712:6598:::::::70:581::16:8:8970:7977:6652:8822:8819:9144:1627:8767:1:28:1279:::::|h[Potion-Stained Cloak]|h|r"
ttname = "GameTooltip"
(for index) = 4
(for limit) = 21
(for step) = 1
i = 4
left = GameTooltipTextLeft4 {
 0 = <userdata>
}
text = "Upgrade Level: 10/13"
perLevelUpgradeCost = nil
priceToMax = nil
Icon = nil
itemString = "-cffa335ee-Hitem:193712:6598:::::::70:581::16:8:8970:7977:6652:8822:8819:9144:1627:8767:1:28:1279:::::-h[Potion-Stained Cloak]-h-r"
_ = "-cffa335ee-Hitem"
_ = "193712"
_ = "6598"
_ = ""
_ = ""
_ = ""
_ = ""
_ = ""
_ = ""
_ = "70"
_ = "581"
_ = ""
_ = "16"
NumBonusIDs = "8"
BonusID1 = "8970"
BonusID2 = "7977"
BonusID3 = "6652"
BonusID4 = "8822"
BonusID5 = "8819"
BonusID6 = "9144"
bonusIDList = <table> {
 1 = 8970
 2 = 7977
 3 = 6652
 4 = 8822
 5 = 8819
 6 = 9144
}
(for index) = 1
(for limit) = 8
(for step) = 1
j = 1
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 MythicPlus = <table> {
 }
}
(for control) = "MythicPlus"
sort = "MythicPlus"
IDs = <table> {
 Icon = "|T463447:14|t"
 MaxRank = 13
 Ranks = <table> {
 }
}
currentRank = 10
ranksToGo = 3
(*temporary) = "itemEquipLoc INVTYPE_CLOAK"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on local 'perLevelUpgradeCost' (a nil value)"

**Comment by Arco-Dielhof** [comment]
Heyy, thank you for the error report, as well as already a fix. Will add it to next build (hopefully before the weekend).

**Comment by Markiv3** [comment]
I also found out that INVTYPE_ROBE and INVTYPE_SHIELD are missing.

**Comment by Arco-Dielhof** [comment]
They should all be fixed in the latest version!
