### ISSUE TITLE
Attempt to index local 'text' (a nil value)

### ISSUE THREAD

**Issue by Hollicsh** [AzerPUG/ToolTips#28]
20x AzerPUGsToolTips/ToolTips.lua:149: attempt to index local 'text' (a nil value)
[string "@AzerPUGsToolTips/ToolTips.lua"]:149: in function `SearchGenericUpgradeableItem'
[string "@AzerPUGsToolTips/ToolTips.lua"]:16: in function <AzerPUGsToolTips/ToolTips.lua:15>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "@ElvUI/Core/General/ItemLevel.lua"]:81: in function `GetGearSlotInfo'
[string "@ElvUI/Core/Modules/Misc/InfoItemLevel.lua"]:253: in function <...aceElvUI/Core/Modules/Misc/InfoItemLevel.lua:239>
[string "=[C]"]: in function `UpdatePageInfo'
[string "@ElvUI_SLE/modules/armory/armory.lua"]:489: in function <ElvUI_SLE/modules/armory/armory.lua:485>
[string "=[C]"]: in function `?'
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...ies/Core/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@ElvUI_Libraries/Core/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@ElvUI_Libraries/Core/Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <...UI_Libraries/Core/Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = <table> {
 GetSpecificAddonVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:274
 WeapValorCostList = <table> {
 }
 ItemUpgrades = <table> {
 }
 FillOptionsPanel = <function> defined @AzerPUGsToolTips/ToolTips.lua:89
 GetUpgradeCostForItem = <function> defined @AzerPUGsToolTips/ToolTips.lua:204
 SearchGenericUpgradeableItem = <function> defined @AzerPUGsToolTips/ToolTips.lua:141
 RankBonusID = <table> {
 }
 OnLoadCore = <function> defined @AzerPUGsToolTips/ToolTips.lua:25
 ReceiveVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:259
 OnEvent = <function> defined @AzerPUGsToolTips/ToolTips.lua:296
 OnLoadSelf = <function> defined @AzerPUGsToolTips/ToolTips.lua:35
 Currencies = <table> {
 }
 Events = <table> {
 }
 ShareVersion = <function> defined @AzerPUGsToolTips/ToolTips.lua:239
 DelayedExecution = <function> defined @AzerPUGsToolTips/ToolTips.lua:224
 OnLoadBoth = <function> defined @AzerPUGsToolTips/ToolTips.lua:14
 StaticSlotValorCost = <table> {
 }
 StackUpgradeCosts = <function> defined @AzerPUGsToolTips/ToolTips.lua:187
}
clipAfter = 35
searchValue = "Уровень улучшения: "
_ = nil
itemLink = nil
ttname = "GameTooltip"
(for index) = 3
(for limit) = 6
(for step) = 1
i = 3
left = GameTooltipTextLeft3 {
 0 = <userdata>
}
text = nil
(*temporary) = GameTooltipTextLeft3 {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = "Уровень улучшения: "
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'text' (a nil value)"

**Comment by Arco-Dielhof** [comment]
I am unable to replicate this error, can you give a bit more context when it happened?

**Comment by Hollicsh** [comment]
When I inspect a character, I hover over an item with the mouse and I get this error.

**Comment by Arco-Dielhof** [comment]
Is it still happening with the update from yesterday?

**Comment by Hollicsh** [comment]
No. Now it's fine !
