### ISSUE TITLE
Implement Legendary Functionality

### ISSUE THREAD

**Issue by Arco-Dielhof** [AzerPUG/ToolTips#5]
- Scan tooltip for "Shadowlands Crafted Legendary (1)" (fish that out as constant, like with clipAfter / searchValue).
- If line is in there, check what iLevel the leggo is.
- Add line directly under 'Shad Crafted Leggo (1)', containing upgrade value in soulash.

**Comment by royb3** [comment]
It has been implemented using bonus IDs instead.
