### ISSUE TITLE
Move Legendary upgrade costs line upwards.

### ISSUE THREAD

**Issue by royb3** [AzerPUG/ToolTips#7]
We have tried several ways to try the line upwards, underneath the unique equipped line. Initially, this broke the addon, changing the anchors worked, but now in tooltips over chat.

A new implementation where the text and color of all lines are copied and moved down is still being made.

**Comment by Arco-Dielhof** [comment]
Change it to be right after the ItemLevel line, instead of at the bottom. Can not be on the upgrade rank line, since it does not have that line on Legendaries.
